### ISSUE TITLE
standardize sweeper reporting

### ISSUE THREAD

**Issue by eneemann** [agrc/sweeper#10]
The reporting format needs to be determined and standardized across the functions so a consistent report is provided.

**Comment by steveoh** [comment]
What are some of the useful metrics that we can extract during processing?

That should help determine the format

**Comment by eneemann** [comment]
* Empty Geometries
  * ObjectID or other unique ID
  * Issue (empty geometry)

* Duplicates
  * ObjectID or other unique ID
  * Issue (duplicate)
  * Type of duplicate

* Invalid Geometry
  * ObjectID or other unique ID
  * Issue (invalid geometry)
  * Type of invalid geometry

**Comment by steveoh** [comment]
I think we got this pretty good also.
