### ISSUE TITLE
complete docopt CLI

### ISSUE THREAD

**Issue by eneemann** [agrc/sweeper#11]
The docopt CLI needs to be completed so the different functions can be called by the main script. depending on what the user wants to accomplish.

**Comment by steveoh** [comment]
Brainstorm some options, and leave them in a comment for everyone, that would be relevant for your tool so we can have some guidance for when we design the cli.

**Comment by eneemann** [comment]
Main functions should be called on individual feature classes
* Sweep empties
  * option to get_report
  * option to try_fix
* Sweep duplicates
  * option to get_report
  * option to try_fix
* Sweep invalids
  * option to get_report
  * option to try_fix
  * option to delete (?) - not sure if this would be advisable

**Comment by steveoh** [comment]
let's call this done and open specific issues with the cli
