### ISSUE TITLE
Standardize Address Parts

### ISSUE THREAD

**Issue by stdavis** [agrc/sweeper#24]
The address parser should be able to format these address parts:
- [x] Street Types (`ST`, `WAY`, `HWY`, etc)
- [x] Cardinal Directions - Single letters are preferred (`N`, `S`, `E`, `W`)
- [x] Unit Types (`Suite`, `Apt`)
- [x] PO Boxes

The sweeper task would report non-standard values as issues and could attempt to fix them if the `--try-fix` flag is passed.

Are there any other types that I'm missing?

Where can I get a list of the values that are accepted as standards for each of these address parts? The lowest hanging fruit is the cardinal directions. Is the preference single capital letters (`N`, `S`, `E`, `W`)?

Ping @rkelson @ZachBeck @eneemann @gregbunce

**Comment by gregbunce** [comment]
I can provide a list of valid roads/address points street types.

**Comment by eneemann** [comment]
I'll let @gregbunce verify, but I believe single capital letters (N, S, E, W) is the preference for prefix and suffix directions.  That is what we have as the code in our UTRANS domains.

For the cardinal directions, maybe we need to specify that the address parts are "prefix direction" and "suffix direction"?

**Comment by steveoh** [comment]
as long as it is consistent that works for me. The geocoders score better with the spelled out version but the web api handles that.

**Comment by stdavis** [comment]
@eneemann Does this comment from you fit into this issue?
>Ensure street type is used consistently (specifically, enforcing that 'ST' is used on Center/Main)

Are you saying that there should never be `Main Dr`? If so, can you get me specifics?

**Comment by eneemann** [comment]
> @eneemann Does this comment from you fit into this issue?
> 
> > Ensure street type is used consistently (specifically, enforcing that 'ST' is used on Center/Main)
> 
> Are you saying that there should never be `Main Dr`? If so, can you get me specifics?

I don't explicitly mean there should never be a "Main Dr" (though there are probably very few).  What I mean is that I know of some cities that don't put a street type on Main St or Center St.  Their addresses are just "123 Main" or "456 Center."  I just want to make sure we catch those, and think standardizing them to add "St" as a street type for Main or Center, when the street type is missing, would probably improve results.

**Comment by stdavis** [comment]
Ah, OK, thanks for the clarification. This sounds reasonable to me.

**Comment by gregbunce** [comment]
Here's the list of valid street types in the SGID
https://docs.google.com/spreadsheets/d/1Ypu1plR1hTH57KdICIqwGu1q4djnnNuaWXhyDEC6F0I/edit#gid=0

**Comment by stdavis** [comment]
Any preferences on PO Box format? 

@steveoh What's the preferred format for the web api?

**Comment by stdavis** [comment]
FYI - For the street type standardization, I took the types from @gregbunce's [doc](https://docs.google.com/spreadsheets/d/1Ypu1plR1hTH57KdICIqwGu1q4djnnNuaWXhyDEC6F0I/edit#gid=0) above and then mapped the values from the [USPS abbreviations doc](https://github.com/agrc/agrc.python/blob/master/agrc/data/USPS_Street_Suffixes.csv) to create a [json file](https://github.com/agrc/sweeper/blob/address-parser/src/sweeper/street_types.json) and included it in this project. This means that it's open to changes more than the old parser. I believe that this will make @rkelson happy. :)

**Comment by steveoh** [comment]
i prefer `P.O. Box 1`

**Comment by rkelson** [comment]
that will make @rkelson very happy

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by steveoh** [comment]
this is the map I use @stdavis in the web api https://github.com/agrc/api.mapserv.utah.gov/blob/7c7fdb6cdacae3be3e0f31bbcb04e7a7d49e54ec/WebAPI.API/App_Start/CacheConfig.cs#L57-L176
