### ISSUE TITLE
Address Parser Module Design

### ISSUE THREAD

**Issue by stdavis** [agrc/sweeper#25]
There obviously needs to be a module in `src/sweepers` that defines the `sweep` and `try_fix` methods. But if this is going to be a new replacement for https://github.com/agrc/agrc.python/blob/master/agrc/parse_address.py, there needs to be a way for users to use the parsing logic outside of the main sweeper process. My proposal would be to keep the core address parsing logic in a separate module (still within the sweeper project) that could be imported and used directly.

An example of how it could be used outside of the sweeper process in a custom script:
```python
from sweeper import addressParser

parsed = addressParser.parse('123 S Main St')
```

Does anyone have issues with this or ideas on how it could be done better?

Ping @ZachBeck @rkelson

**Comment by ZachBeck** [comment]
yeah, that would be my vote as well. In my mind parsing vs sweeping are 2 different things

**Comment by steveoh** [comment]
I think you should expose parse as a method from the sweeper. Otherwise it might be too different to fit into the goals of this module.

```py
from sweeper.sweepers.addresses import AddressSweeper

tool = AddressSweeper(yada yada)

report = tool.sweep(yada)
report = tool.try_fix(yada)
address_parts = tool.parse('123 S Main St')
```

After writing this it doesn't seem to make sense to have to pass in the ctor params for the sweeper just to use the parse method. 

Maybe we move report, backup and workspace info into some namespaces and fit the address parsing into there in a way like you are describing above.

**Comment by stdavis** [comment]
Here's what the API looks like currently as part of #35...
```python
from sweeper.address_parser import Address

address = Address('123 1/2 S Main Street')
print(address.address_number)           #: '123'
print(address.address_number_suffix)    #: '1/2'
print(address.address_prefix_direction) #: 'S'
print(address.street_name)              #: 'MAIN'
print(address.street_type)              #: 'ST'
print(address.normalized)               #: '123 1/2 S MAIN ST'

address = Address('123 N 700 East')
print(address.street_name)              #: '700'
print(address.street_direction)         #: 'E'
```

@ZachBeck & @rkelson: How does that look to you? I believe that you two would be the main users of this module so I want to make it work for you. I did change the format of the parsed object's property names to make them compliant with our python style and closer to the address points field names. This would require minor updates to your existing code that uses the `agrc.address_parser` module.

**Comment by rkelson** [comment]
This is looking great. Just talked to Zach and he uses the library just for
the parsing functionality and I just the normalizing in case you were
wondering.
Do you have a list for, or will it be in the documentation for the new
library, all the parsed objects available? Also, what happens if you added
an apartment/unit/suite/... number to the address?
 ex.
123 1/2 S Main Street #3
123 1/2 S Main Street Unit 4
123 1/2 S Main Street Suite #5

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by ZachBeck** [comment]
Looks good. I think there are some cases in the address points where the address number suffix is a letter ie 123 A S Main St

**Comment by stdavis** [comment]
> Do you have a list for, or will it be in the documentation for the new library, all the parsed objects available?

[I will commit to having good docs for this module](https://github.com/agrc/sweeper/issues/37). For now, here's the list of parsed address parts:
![image](https://user-images.githubusercontent.com/1326248/68716126-c2b71880-0560-11ea-9885-0eef80cda1c0.png)
The keys of this dictionary are the available parts from `usaddress` and the values are the properties of the `Address` class that I'm mapping them to.

Are there any that are currently commented out that you'd like me to turn on? Or are there any property names that you'd like me to change?

**Comment by stdavis** [comment]
> Also, what happens if you added an apartment/unit/suite/... number to the address?

![image](https://user-images.githubusercontent.com/1326248/68716711-170ec800-0562-11ea-9d7f-4ae63a62082d.png)

@rkelson Is this what you were expecting? If not, how can I make it better?

**Comment by stdavis** [comment]
> I think there are some cases in the address points where the address number suffix is a letter ie 123 A S Main St

![image](https://user-images.githubusercontent.com/1326248/68716949-ae741b00-0562-11ea-8f98-df982309736a.png)

@ZachBeck Does this look correct to you?

**Comment by ZachBeck** [comment]
For unit types and numbers, the only time I use '#' is if there is no unit type
123 S Main St # 3 vs 123 S Main St Suite 3

**Comment by stdavis** [comment]
> For unit types and numbers, the only time I use '#' is if there is no unit type

@ZachBeck Do the example below capture what you are requesting?

`unit_id` is prefixed with a `#` character if there is no `unit_type` found
```
Address('123 s main st 3')
Parsed Address:
{'address_number': '123',
 'normalized': '123 S MAIN ST #3',
 'prefix_direction': 'S',
 'street_name': 'MAIN',
 'street_type': 'ST',
 'unit_id': '#3'}
```

No `#` since there is a `unit_type`
```
Address('123 s main st suite 3')
Parsed Address:
{'address_number': '123',
 'normalized': '123 S MAIN ST SUITE 3',
 'prefix_direction': 'S',
 'street_name': 'MAIN',
 'street_type': ',
 'unit_id': '3',
 'unit_type': 'SUITE'}
```

`#` is stripped because there is a `unit_type`
```
Address('123 s main st suite #37 3')
Parsed Address:
{'address_number': '123',
 'normalized': '123 S MAIN ST SUITE 3',
 'prefix_direction': 'S',
 'street_name': 'MAIN',
 'street_type': ',
 'unit_id': '3',
 'unit_type': 'SUITE'}
```

**Comment by rkelson** [comment]
Scott I think you are doing an exceptional job. I am sure v.2.0 is going to
be a great improvement. I have no further input at this time.

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by ZachBeck** [comment]
I don't know if it makes a difference but David Buell always wanted a space after the # i.e. # 7

**Comment by stdavis** [comment]
> I don't know if it makes a difference but David Buell always wanted a space after the # i.e. # 7

`usaddress` does that out-of-the-box. I updated my example above.

**Comment by stdavis** [comment]
I'm closing this issue since there are no major concerns with the module design and I have addressed all of the other feedback.
