### ISSUE TITLE
Minimum Address Parts

### ISSUE THREAD

**Issue by stdavis** [agrc/sweeper#28]
From @steveoh 
>making sure there are the minimum addresses parts would be helpful and reporting what might be missing

As part of this issue, the names of the different address parts need to be decided upon (e.g. `suffixDirection`, `prefixDirection`, etc).

**Comment by stdavis** [comment]
Proposed list of required parts:
- `address_number`
- `street_name`
- `street_direction` or `street_type`

--OR--

- `po_box`

Seem reasonable?

This also seems like it should be a part of the sweeper, not the parser.

**Comment by steveoh** [comment]
street direction and type are not required for a geocode to complete. 

Since a street can only exist in one address quadrant and a street name can only have one street type the last two parts are not required. 

eg: 2222 atkin only exists in the east address quadrant and atkin is only an avenue street type.

If you differentiate errors from warnings, this could be a warning since the parser will not know these caveats.

**Comment by stdavis** [comment]
> Since a street can only exist in one address quadrant and a street name can only have one street type...

Do the roads data really follow this rule?

Ping @gregbunce, @eneemann

**Comment by eneemann** [comment]
I believe there are cases where streets lie on address system and/or quadrant lines and technically have a different system/quadrant on the left and right sides.  Therefore a street could have two quadrants.  Similarly, if a street is along a municipal boundary, it could have a different name and street type, one for each municipality.  Depending on how that's handled in the system, one name and type could be an alias or there could be two segments on top of each other (one for each municipality).  An alias might also have a different street type.  These cases would likely be a small percentage of the data set.

**Comment by steveoh** [comment]
> > Since a street can only exist in one address quadrant and a street name can only have one street type...
> 
> Do the roads data really follow this rule?
> 
> Ping @gregbunce, @eneemann

The road grinder project that the locators use follow this rule
