### ISSUE TITLE
Add Missing Street Types in Certain Circumstances

### ISSUE THREAD

**Issue by stdavis** [agrc/sweeper#32]
From @eneemann:
>Ensure street type is used consistently (specifically, enforcing that 'ST' is used on Center/Main)
>I don't explicitly mean there should never be a "Main Dr" (though there are probably very few). What I mean is that I know of some cities that don't put a street type on Main St or Center St. Their addresses are just "123 Main" or "456 Center." I just want to make sure we catch those, and think standardizing them to add "St" as a street type for Main or Center, when the street type is missing, would probably improve results.

**Comment by stdavis** [comment]
@ZachBeck @steveoh Any reservations on this idea from Erik? Should we be adding `ST` to Main and Center street names if they are missing a street type? Will that help with geocoding? Do we want to be added data like this?

It seems reasonable to me. I've never heard of a Main or Center without a street type.

**Comment by ZachBeck** [comment]
I don't have any reservations, I think it would solve more problems than it would create.

**Comment by steveoh** [comment]
The road grinder project builds addresses where the street type is not required since there is no other street type for that address. The post office, when they standardize an address, removes the street type in the same scenarios from what I can tell. 

I dont have any reservations adding it, but I think you would need the road grinder data to know what street type to use.

**Comment by stdavis** [comment]
> I think you would need the road grinder data to know what street type to use.

I think that the current proposal is to add `ST` to all `Center` and `Main` street names. Are you suggesting that there might be other street type/name combinations?

**Comment by steveoh** [comment]
If you can guarantee, based on our data, that there are st is the only post type for those road names then I am ok with it.

**Comment by eneemann** [comment]
Maybe this is a moot issue if addresses without a street type can be handled okay.  I just search our SGID roads and `NAME LIKE 'MAIN' OR NAME LIKE 'CENTER'` returned 4139 results.  Of those, only 31 had street types that were not 'ST', 2 of which had not street type (`(NAME LIKE 'MAIN' OR NAME LIKE 'CENTER') AND (POSTTYPE <> 'ST')`)

**Comment by steveoh** [comment]
I agree with the moot issue. I think this would be an improvement if we inspected the roads but it was already decided we were not going to do that.

**Comment by stdavis** [comment]
I'm going to close this for now. Feel free to reopen if there are other actionable ideas related to this.
