### ISSUE TITLE
Create Docs for `sweeper.address_parser`

### ISSUE THREAD

**Issue by stdavis** [agrc/sweeper#37]

**Comment by stdavis** [comment]
Completed in fea13908a002ffe0876ed2c04f68a3d4c9e451a2

**Comment by stdavis** [comment]
Here are the docs: https://github.com/agrc/sweeper/tree/address-parser#parsing-addresses

@rkelson Am I missing anything? We do need to figure out how to distribute this package but I think that's a bigger issue for this project.

**Comment by rkelson** [comment]
Forgive me I am still trying to get back up to speed after my trip and
there are a lot of *mentions* and *slacking *going around. I think the
documentation looks good and I will let you know if I think It should have
additions when I go to install and consume.

But yeah, the distribution part was something I was wondering about,
especially when it pertains to the street type json file changes, but I am
sure you will figure out what is best. I still need to get a better handle
on github outside of gitpages.

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov
