### ISSUE TITLE
991 vista east fork

### ISSUE THREAD

**Issue by steveoh** [agrc/sweeper#43]
```py
{'address_number': '991',
 'normalized': '991 VISTA EAST FRK',
 'street_name': 'VISTA EAST',
 'street_type': 'FRK'}
```

street type should be `vista east frk`. @rkelson says `frk` is not a valid street type in utah.

**Comment by stdavis** [comment]
You mean that _street_name_ should be `vista east frk`, right?

**Comment by rkelson** [comment]
I don't think FRK is a valid utah street type but that is my opinion and it
probably varies by location. I am pretty sure I checked and for that
address FORK was spelled out in the roads data.

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by rkelson** [comment]
I don't know that you should take it that far but do what makes you feel
best. We can strive for perfection but nothing is perfect. And you know how
the saying goes, 'you are....if you do and....if you don't. I am actually
somewhat indifferent about this as the address points are our authoritative
address dataset, not the parcels. There are also rules such as #6 &7 to
follow. This particular address was just one I picked and think I actually
made it up that steve ran through the wizzywigger. Either way I think you
are doing a great job.

BTW Fork is not in the pre approved AGRC_Street_Suffixes.csv but I digress.

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by steveoh** [comment]
We can't say that fork is not a street type because it's not in our approved list when counties are assigning it to streets. We need to match reality.

**Comment by stdavis** [comment]
I'm going to close this issue for now. Let me know if there's something to be done that I missed.
