### ISSUE TITLE
State Routes SR

### ISSUE THREAD

**Issue by ZachBeck** [agrc/sweeper#45]
Addresses like 910 S SR 22 or 1910 N US HWY 89
will return 22 and 89 for the street_name

**Comment by steveoh** [comment]
The web api and I believe the transportation.roads data standardized on highway abbreviated as hwy. If we want to keep that consistent, sr 22 should become hwy 22.

**Comment by ZachBeck** [comment]
Agreed. In the address points I've been trying to return hwy for all state and US highways.

**Comment by stdavis** [comment]
Just to be clear:
`910 S SR 22` currently parses to this:
```
{'StreetNamePreType': 'SR',
 'address_number': '910',
 'normalized': '910 S 22',
 'prefix_direction': 'S',
 'street_name': '22'}
```

(`StreetNamePreType` is a `usaddress` thing.)

We want to update the parser to parse this address to this:
```
{'address_number': '910',
 'normalized': '910 S HWY 22',
 'prefix_direction': 'S',
 'street_name': 'HWY 22'}
```

And `1910 N US HWY 89` should be parsed to this:
```
{'address_number': '1910',
 'normalized': '1910 N HWY 89',
 'prefix_direction': 'N',
 'street_name': 'HWY 89'}
```

No difference between state routes or US highways? 

@ZachBeck, @steveoh, & @rkelson: I'd love feedback.

**Comment by ZachBeck** [comment]
Correct, there should be no difference between state routes and US highways, both should be HWY.
There was also a similar case in the address 1106 S OLD HWY 89 where 89 was returned as the street_name but it should have been OLD HWY 89
