### ISSUE TITLE
Numeric street names with E for a unit id

### ISSUE THREAD

**Issue by ZachBeck** [agrc/sweeper#46]
1050 E 470 S E will get the address correct but will not return E as the unit id.
1106 S OLD HWY 89 E will return E as the unit id correctly.

There are some cases where # is incorrectly being added to unit id's when there is no unit type.

**Comment by stdavis** [comment]
> There are some cases where # is incorrectly being added to unit id's when there is no unit type.

@ZachBeck Can you give me an example?

**Comment by ZachBeck** [comment]
1106 S OLD HWY 89 A will return '# A'

**Comment by stdavis** [comment]
So what about an input address of `123 S Main Street #3`? Would you like all `#`s stripped? What's the standard way that we want to format unit/apt numbers? Or do we try not to touch them at all?

**Comment by ZachBeck** [comment]
In your example I format the full address in the address points as 123 S Main Street # 3 (the space after the # was a David Buell thing, I don't know if it matters). For the unit id I always strip the #. Some counties have special characters like - or / that I leave in the unit id because I have no way of knowing if it's right or wrong.

**Comment by stdavis** [comment]
@steveoh How does the geocoder feel about unit/apt/suite numbers? Is there a format that I can put stuff in that it will like better than another?

**Comment by steveoh** [comment]
currently i attempt to strip them out. So no unit is the best unit for geocoding.

**Comment by stdavis** [comment]
I don't think that we want this project stripping them out. But is there a format that we can put them in to make it easier for the geocoder to strip them out?

**Comment by steveoh** [comment]
`unit n` is a good way. `#` has a special meaning in uri's so I would avoid that. This is the full list of [abbreviations](https://github.com/agrc/api.mapserv.utah.gov/blob/7c7fdb6cdacae3be3e0f31bbcb04e7a7d49e54ec/WebAPI.API/App_Start/CacheConfig.cs#L184-L207) that we use in the API.

**Comment by stdavis** [comment]
I think that we are pretty close on this one without going too far down the hole of personal opinion. It no longer incorrectly returns unit types and returns reasonably formatted addresses. Closing for now.
