### ISSUE TITLE
Metadata Tags

### ISSUE THREAD

**Issue by stdavis** [agrc/sweeper#47]
Ref: https://docs.google.com/document/d/1VkXRwfSn6MraI1VeLfei5tg6je4bd2pp_Vh1JuST9xs/edit

- [x] All datasets should have at least the `SGID` and `AGRC` tags as well as the ISO category.
- [x] All words should be title-cased except for articles and abbreviations (see agol-validator for specifics).
- [x] Implement try-fix that adds the database and schema tags and fixes bad casing

**Comment by steveoh** [comment]
I'm not sure how this fits or overlaps with @jacobdadams agol validator so maybe it is worth a little discussion. 

I am under the impression that the agol validator manages tags. Is the idea here that the source data should have the tags as the agol validator would set them so it doesn't have to do any work?

Is this sweeper going to be used for other agency data that wants to share to our open data? Would the same rules apply?

**Comment by jacobdadams** [comment]
agol-validator was built to just handle the set of tags exposed by an AGOL item's item.tags property in the ArcGIS API for Python, which are the tags we see on the item's AGOL page. It runs on every Feature Service item in UtahAGRC's folders. It proper cases the tags, deletes any tags in a defined list (currently `.sd` and `service definition`), removes any tags that occur in item.title, and adds SGID category, `SGID`, and `AGRC` if the item is in META.AGOLItems.

I believe, but need to test, that tags in the metadata will override the AGOL item's tags if/when the metadata is uploaded to the AGOL item using arcpy.metadata and the ArcGIS API for Python. agol-validator does this upload as part of its fixes.

I think it's a good idea to clean the tags in the database as well with sweeper, under the principle that the database's metadata is considered the source of truth. agol-validator will still double check (especially for other items that are not in META.AGOLItems), but if we've got one source of truth, lets keep it truthy.

**Comment by stdavis** [comment]
> database's metadata is considered the source of truth
👍👍👍
