### ISSUE TITLE
problem address

### ISSUE THREAD

**Issue by rkelson** [agrc/sweeper#55]
Addresses throwing exceptions:

- [x] 2430 N RIVER VIEW WAY
- [x] 135 S RIVER BEND WAY
- [x] 1384 S CANYON CREST
- [ ] 1361 N 1075 WEST UNIT 12 BLDG B
- [ ] 860 S 1625 EAST UNIT C BLDG 27
- [x] 728 S WATER MILL WAY
- [x] 1623 E POETS REST
- [x] 1623 E POETS RST
- [x] 2362 S 3340 WEST CIR

**Comment by rkelson** [comment]
1630 W 2000 S Bldg 101 -> 1630 W 2000 S

'Bldg' get removed

**Comment by rkelson** [comment]
'1940 E 5625 S' returns normalized address '1940 E # 5625 S'

for some reason the '#' gets added

**Comment by rkelson** [comment]
'957 PATTERSON ST REAR' returns normalized address '957 PATTERSON ST # REAR'

not sure if anything can be done with these. There are only about 40 in weber

**Comment by steveoh** [comment]
> '957 PATTERSON ST REAR' returns normalized address '957 PATTERSON ST # REAR'
> 
> not sure if anything can be done with these. There are only about 40 in weber

I think the normalized output is correct for these invalid addresses. I would fix this in the calling code.

**Comment by rkelson** [comment]
yea that was an accidental closure

Rick Kelson
Utah AGRC
385.313.0798
gis.utah.gov

**Comment by stdavis** [comment]
Thanks for the info in this ticket, @rkelson! I may not get to it soon, but I will definitely work through these at some point.

**Comment by rkelson** [comment]
you know I am finding a lot of weird stuff that stops my code in it's trax

Rick Kelson
Utah AGRC
385.313.0798
gis.utah.gov

**Comment by stdavis** [comment]
Using try...except may help you at least ignore these issues for the time being.

**Comment by rkelson** [comment]
yeah on my list to learn....I guess the time is now, or monday

Rick Kelson
Utah AGRC
385.313.0798
gis.utah.gov

**Comment by stdavis** [comment]
```python
try:
	address = Address('123 a really bad address')
except:
	continue #: or some other code to deal with the address parser throwing an error
```

**Comment by stdavis** [comment]
@rkelson Is `2362 S 3340 WEST CIR` really a valid address?

**Comment by stdavis** [comment]
Same question about these addresses:
`1361 N 1075 WEST UNIT 12 BLDG B`
`860 S 1625 EAST UNIT C BLDG 27`
Not sure what I should be doing with them. Strip the building or unit? Somehow combine them?

**Comment by stdavis** [comment]
`1940 E 5625 S` is incorrectly parsed as:

```
Parsed Address:
{'address_number': '1940',
 'normalized': '1940 E # 5625 S',
 'street_direction': 'E',
 'unit_id': '# 5625 S'}
```

I believe that this is an upstream issue with `usaddress` and submitted an issue: https://github.com/datamade/usaddress/issues/283

I also added a failing test to this project so that we can track this issue.

**Comment by rkelson** [comment]
I am not sure what addresses are valid or not. The parcels come with all sorts of addresses and values in the address field. I am still trying to figure out how the sweeper works, what it does and does not do, and how to deal with the exceptions. In the smaller counties there are only a few exceptions to deal with but when I run Utah County it throws over 440 exceptions. Some are junk addresses but some are as valid as the days are long.
What is the problem with "12673 N ANGELS GATE"? I get this error and it seems to be the most common:
    raise InvalidStreetTypeError(type_text)
sweeper.address_parser.InvalidStreetTypeError

**Comment by stdavis** [comment]
`InvalidStreetTypeError` means that the street type (`GATE`, I assume) does not show up in https://github.com/agrc/sweeper/blob/master/src/sweeper/street_types.json. I wonder if this should be switched to more of a warning, than an error so that it doesn't throw an exception...

**Comment by rkelson** [comment]
Seems like a great idea. Maybe it is just me but I think there are many valid addresses, aside of numeric street names, that don't have a street type.

**Comment by rkelson** [comment]
I mentioned it before but IMO the street type list is too far reaching for Utah. I just did a quick look at the roads data and there are no records where the following are a street type (posttype); they are part of the name. 
Ranch
Trail
Vista 
Estates
Flat
Glen
Grove
Hill (has 2 records for 'Boat Ramp Hill), the rest are part of the name
Heights
Junction
Meadow
Point
Terrace
Terraces
Village

**Comment by ZachBeck** [comment]
Address points have a bunch of those street types:
Ranch
Trail
Glen
Grove
Hill
Heights
Meadow
Point
Terrace
Village

I checked Heights, Point and Terrace and those are in the roads.

**Comment by rkelson** [comment]
Yes, yes Zach is right. I was doing the wrong query.

**Comment by stdavis** [comment]
I think that part of the problem is that usaddress is going to parse these words as street types no matter what. If they don't show up in our list of street types, then I just assume they are part of the street name and append them and remove set the street type back to None. Then no error or warning would be thrown.

**Comment by rkelson** [comment]
Yeah I don't have the answer. There are cases both ways were it is part of the name or a street type. I think I have a rule for this ;)

**Comment by stdavis** [comment]
@rkelson I just pushed v1.0.6 to pypi. Run `pip install agrc-sweeper -U` and give it another try and let me know how it's working.

**Comment by eneemann** [comment]
@stdavis I just finally upgraded to Pro 2.5 and am starting to experiment with your address parser.

**Comment by eneemann** [comment]
> Same question about these addresses:
> `1361 N 1075 WEST UNIT 12 BLDG B`
> `860 S 1625 EAST UNIT C BLDG 27`
> Not sure what I should be doing with them. Strip the building or unit? Somehow combine them?

Maybe these could be converted to 'UNIT B12' and 'UNIT C27'?  That way you could include the building in the unit number?  Although it wouldn't explicitly state the building part.

**Comment by stdavis** [comment]
Doesn't look like usaddress is interested in addressing this issue: https://github.com/datamade/usaddress/issues/283

The best workaround that I've found is to append ", Utah" to the end of the addresses. Here's another example that I ran into today in while working on masquerade:
![image](https://user-images.githubusercontent.com/1326248/101422916-1788a800-38b5-11eb-942c-6e1c13237c0e.png)

I wonder if I should just be adding ", Utah" (unless it already exists) to all addresses. I may experiment with this.

@rkelson How did you testing on Pro 2.5 end up going?

**Comment by rkelson** [comment]
@stdavis  I ended up just writing a bunch of exceptions specific to each county (ex. West Temple) although I just let all the addresses like @eneemann mentioned (Utah Co has many of them) with units and building or appt numbers slide. The arguments that many of the addresses provided are not valid addresses got real old real quick and there is not a lot that can be done with them without case by case exceptions. In many counties I am trying to use the address points for the address after all the work that is done to them. I also decided to follow rules #1, #3, and #5 and promote the address points as the authoritative address source from AGRC. 
![image](https://user-images.githubusercontent.com/6200941/101500887-4a21b780-392c-11eb-9604-a49dccba57ad.png)
I don't think we should be appending `, Utah` to the addresses.

**Comment by stdavis** [comment]
> I don't think we should be appending `, Utah` to the addresses.

I wasn't clear. I meant that I may try appending `, Utah` to incoming addresses behind the scenes before I send the address to the usaddress parser. Adding the state seems to help the machine learning in usaddress do a better job of parsing out the different address parts. You would never see it from your end other than maybe an additional `state` property on the parsed address object. I wouldn't include it in the normalized address text.

**Comment by eneemann** [comment]
I just think it's interesting that usaddress employs a machine learning algorithm and that they don't have specific rules.
