### ISSUE TITLE
Addresses with “#th” streets

### ISSUE THREAD

**Issue by stdavis** [agrc/sweeper#57]
Valuable feedback from @msilski at WFRC...
>Ex. No match found for 2040 S 23RD E in Salt Lake City
>Ex. No match found for 70 N 2ND E in American Fork
>Solution? replace #th characters with 00 if 2 explicit directionals are present

Currently, `2040 S 23RD E` is parsed like this:
![image](https://user-images.githubusercontent.com/1326248/81129393-675b5700-8f01-11ea-9a38-7be34a310828.png)

We could do a regex on street names looking for `th` and `rd` (are there any others?) and replace them with `00`.

**Comment by steveoh** [comment]
that is a good idea. We also have a proposal to add these as aliases to the road grinder project

**Comment by steveoh** [comment]
Are there others...

```
1: first, 1st
2: second, 2nd
3: third, 3rd
4: fourth, 4th
5: fifth, 5th
6: sixth, 6th
7: seventh, 7th
8: eighth, 8th
9: ninth, 9th
10: tenth, 10th
11: eleventh, 11th
12: twelfth, 12th
20: twentieth, 20th
21: twenty-first, 21st
22: twenty-second, 22nd
23: twenty-third, 23rd
24: twenty-fourth, 24th
30: thirtieth, 30th
100: one hundredth, 100th
1000: one thousandth, 1,000th
1 million: one millionth, 1,000,000th
1 billion: one billionth, 1,000,000,000th
```

`st`, `nd`, and `th` i think are the three
