### ISSUE TITLE
Old Midvale Address System Addresses

### ISSUE THREAD

**Issue by stdavis** [agrc/sweeper#59]
From @msilski:
>Old Midvale addresses - found five cases of using legacy local address system
Ex. 112 S ALLEN ST in Midvale matched to 112 S ST in Salt Lake City (true location: 7832 S ALLEN ST in Midvale)
Ex. 19 E CENTER ST in Midvale matched to 19 W CENTER ST in Salt Lake City (true location: 684 W CENTER ST in Midvale)

It may not be worth it for only five records in this dataset (DWS employment data). I'm not sure how common these addresses really are. I do remember encountering them when I worked for Sandy City years ago.

**Comment by steveoh** [comment]
These houses all have new addresses right?

**Comment by stdavis** [comment]
Yes.

**Comment by steveoh** [comment]
I don't think this is a path we want to follow. Unless @gregbunce wants to manage the old addresses as alias's or something i think we should continue to focus on currently valid addresses. I would vote to close this as a won't fix

**Comment by stdavis** [comment]
I agree, especially, if we aren't hearing a lot about them.
