### ISSUE TITLE
address sweeping

### ISSUE THREAD

**Issue by steveoh** [agrc/sweeper#6]
The WFRC and a whole bunch of other agencies try to clean their addressing data to produce high match rate geocoding results. We should try to come up with a sweeper that can flag records and possible standardize addresses.

**Comment by stdavis** [comment]
I'd love to work on this. Do we have a set of requirements somewhere?

**Comment by ZachBeck** [comment]
Like format street types, directions, and unit types?

**Comment by steveoh** [comment]
Some of my ideas are to help with address matching are to

- get the unique street names from our roads data and address points. then parse their addresses to the parts and see if the road exists in our data or something similar with levenshtein to catch misspellings
- making sure there are the minimum addresses parts would be helpful and reporting what might be missing
- warning on address reversals 

Another use case is address consistency

- spelling out cardinal directions
- using consistent abbreviations for street, unit, highway

**Comment by stdavis** [comment]
What are your main gripes with https://github.com/agrc/agrc.python/blob/master/agrc/parse_address.py?

**Comment by stdavis** [comment]
From @ZachBeck in slack:
>I think formatting highways US and SR to HWY would be good, and also looking for compound word misspellings like Switchback Way vs Switch Back Way

**Comment by eneemann** [comment]
Maybe the current parser does some of this already
* Clean up internal whitespaces (replace '  ' with ' ')
* Ensure street type is used consistently (specifically, enforcing 'ST' is used on Center/Main)

**Comment by stdavis** [comment]
From @rkelson:
>Looking at my code it looks like there were issues with:
>*Directional with Street Type (ex. North CIR or South ST)
>*Directional and/or Street Type with Unit or Apartment # (i.e. does not change 'North' to 'N')

**Comment by stdavis** [comment]
From @rkelson:
>Looking at my code it looks like there were issues with:
>*Directional with Street Type (ex. North CIR or South ST)
>*Directional and/or Street Type with Unit or Apartment # (i.e. does not change 'North' to 'N')

**Comment by stdavis** [comment]
OK. I _believe_ that I have everything from this issue parsed :) out into separate issues. If I missed something, or if you have more feedback, please let me know.

I'm also still waiting to hear back from Scott F. at WFRC.
