### ISSUE TITLE
Addresses with multiple unit numbers

### ISSUE THREAD

**Issue by stdavis** [agrc/sweeper#63]
Here are a few from [this old issue](https://github.com/agrc/sweeper/issues/55):
```
1361 N 1075 WEST UNIT 12 BLDG B
860 S 1625 EAST UNIT C BLDG 27
```

Currently, these addresses throw exceptions:
```
>>> address_parser.Address('1361 N 1075 WEST UNIT 12 BLDG B')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\projects\sweeper\src\sweeper\address_parser.py", line 67, in __init__
    parts, parsed_as = usaddress.tag(address_text.replace('.', ''), TAG_MAPPING)
  File "C:\Users\agrc-arcgis\AppData\Local\ESRI\conda\envs\sweeper\lib\site-packages\usaddress\__init__.py", line 186, in tag
    label)
usaddress.RepeatedLabelError:
ERROR: Unable to tag this string because more than one area of the string has the same label

ORIGINAL STRING:  1361 N 1075 WEST UNIT 12 BLDG B
PARSED TOKENS:    [('1361', 'AddressNumber'), ('N', 'StreetNamePreDirectional'), ('1075', 'StreetName'), ('WEST', 'StreetNamePostDirectional'), ('UNIT', 'SubaddressType'), ('12', 'SubaddressIdentifier'), ('BLDG', 'SubaddressType'), ('B', 'SubaddressIdentifier')]
UNCERTAIN LABEL:  unit_type

When this error is raised, it's likely that either (1) the string is not a valid person/corporation name or (2) some tokens were labeled incorrectly

To report an error in labeling a valid name, open an issue at https://github.com/datamade/usaddress/issues/new - it'll help us continue to improve probablepeople!

For more information, see the documentation at https://usaddress.readthedocs.io/
```

@eneemann [suggested](https://github.com/agrc/sweeper/issues/55#issuecomment-639104577) that maybe these should be parsed as 'UNIT B12' and 'UNIT 27C'.

At the very least, we should not be passing on the exception from usaddress...

**Comment by steveoh** [comment]
Yes unless they have more than 2 levels of sub address, I agree with Erik they they should be merged in a try catch

**Comment by ZachBeck** [comment]
There might be some cases where the building and unit are both numeric. I don't know if that will cause problems with how you merge the two.

**Comment by steveoh** [comment]
> There might be some cases where the building and unit are both numeric. I don't know if that will cause problems with how you merge the two.

Thanks Zach, that is a good case to know. What would the USPS do in that case? Do they hyphenate or something?

**Comment by stdavis** [comment]
I went with the hyphen on this one. So the `unit_id` for `1361 N 1075 WEST UNIT 12 BLDG B` would be `12-B`.
