### ISSUE TITLE
Replace print statements with python logging

### ISSUE THREAD

**Issue by steveoh** [agrc/sweeper#68]
Python logging can have multiple handlers - console, file, whatever. I would suggest that the standard out (console) handler is always added. If the `--save-report` flag is added then add the file handler. This would be the same as using print with the added benefit that you can filter the severity level. This is [an example](https://github.com/agrc/forklift/blob/master/src/forklift/__main__.py#L252-L265) from forklift.

_Originally posted by @steveoh in https://github.com/agrc/sweeper/pull/67#discussion_r673340264_

**Comment by eneemann** [comment]
I can continue working on this improvement.

**Comment by eneemann** [comment]
Closed with PR #71.
