### ISSUE TITLE
Replace credentials.py

### ISSUE THREAD

**Issue by steveoh** [agrc/sweeper#85]
The credentials.py file is problematic when using the pypi package. Primarily since you do not have access to create or use a credentials.py file when the package is compiled. We need to evaluate some options to bring in this information another way.

The credential file seems to support many things but is mainly used towards automating sweeper right?

```py
DB = ''  #: Full path to sde connection file
CHANGE_DETECTION = '' #: Change detection table name with 'SGID.' prefix
LAST_CHECKED_PATH = '' #: Full path to .last_checked file
REPORT_BASE_PATH = '' #: File path for report CSVs of everything that was fixed; rotated on each run
LOG_FILE_PATH = '' #: File path to log that is rotated on each run
CONNECTIONS = '' #: Dictionary that holds SDE connection file paths
EMAIL_SETTINGS = {  #: Settings for EmailHandler
    'smtpServer': '',
    'smtpPort': 25,
    'from_address': '',
    'to_addresses': '',
    'prefix': f'Auditor on {socket.gethostname()}: ',
}
```

`DB` is the workspace to sweep
`CHANGE_DETECTION` and `LAST_CHECKED_PATH`  is to know what files have changed since the last scheduled run
`REPORT_BASE_PATH` is where to write logs? This seems almost unnecessary and can have a default value and maybe a cli option to overwrite it.
`CONNECTIONS` this is to hold the owner connection files and is very specific to our schema and the automated fixing process
`EMAIL_SETTINGS` this is to email the logs which is great for a set it and forget it automated process

If in #84 we move to a convention based location `CHANGE_DETECTION` and `LAST_CHECKED_PATH` can be removed and replaced with conventions with the opportunity to change through the cli

`DB` is passed in as the workspace and isn't required. Why is it in the credentials also?

`CONNECTIONS`, and `EMAIL_SETTINGS` seem good for some sort of config file. Email should go to sendgrid any only require an api key, but i'll create another issue for that.

Should we move to a convention that inside the folder the cli is run from there should be a json config file and loads the settings from there? Do we continue to shrink the need for the file and look for a `_connections` folder as another convention?

Thoughts?

**Comment by stdavis** [comment]
@steveoh What do you think about using a .env file? This seems like it would be more flexible to me than a JSON file for places like CI.

**Comment by steveoh** [comment]
@stdavis We should chat about it because I don't see this running in CI with arcpy and on prem database access needs.
